In [89]:
import pandas as pd

In [90]:
semisupervised_train=pd.read_csv("semisupervised_train.csv")
print("semisupervised_train>>")
semisupervised_train

semisupervised_train>>


id  cuisine  review_count  rating  recommend
0     3quopZyL8WuqVFfsCi0z2A   indian            98     4.5          1
1     byVmQiGVTyLrG_74OFJ7eg  italian            98     4.0          1
2     X9ftU-exKhTMOjtr3B52rw  chinese            98     4.0          1
3     D9Uf7UmU2KlgS_H8lJwOrA  mexican            98     4.0          1
4     sr0rCMn-XtKATvl9adYQxA  chinese            98     3.5          1
...                      ...      ...           ...     ...        ...
2894  ThderRLd1vYtTFO7LNnP4g    greek             1     5.0          0
2895  CB-2K_Xc0m0DICXxl7evow    latin             1     5.0          0
2896  2s2MwMl7D_khTTKKdMnrgQ    latin             1     5.0          0
2897  d6iU2zIWJOCLUAYXjQLXLA    latin             1     5.0          0
2898  eScKPCTWk7iDPEOt_tedxQ  persian             1     5.0          0

[2899 rows x 5 columns]

In [91]:
semisupervised_train.describe()

review_count       rating    recommend
count   2899.000000  2899.000000  2899.000000
mean      84.957227     3.700931     0.238703
std      128.393346     0.535235     0.426364
min        1.000000     2.500000     0.000000
25%       11.000000     3.500000     0.000000
50%       36.000000     3.500000     0.000000
75%      113.000000     4.000000     0.000000
max     1613.000000     5.000000     1.000000

In [92]:
unsupervised_train=pd.read_csv("unsupervised_train.csv")
print("unsupervised_train>>")
unsupervised_train

unsupervised_train>>


id  cuisine  review_count  rating  recommend
0     p1ohbPwI1QfjHQ2zRup5OA  italian            76     4.0          1
1     uXzHDmzG5mTcjP7IctinKQ   indian            76     4.0          1
2     ceK2VvPlxPBPo1evXOlD7g   indian            76     4.0          1
3     LnsAgGlvIPmc9eV_cMdU5w  mexican            76     4.0          1
4     98NaJ8FWzPuoymHfj6IIeA  chinese            76     3.5          1
...                      ...      ...           ...     ...        ...
1097  p-95dBWK8sxiCvJrUNxZ3Q  chinese             2     2.5          0
1098  EnW3yR9O3yGrjQ9eXEpWFQ  chinese             2     2.5          0
1099  QSYoMQZTkDT8MhoJTQFQdg  chinese             2     2.5          0
1100  b1OAb3zbmNnMAG9xqtttfg  chinese             2     2.5          0
1101  IHUq8aaR8_RsLGgspZhQGw   indian             2     2.5          0

[1102 rows x 5 columns]

In [93]:
unsupervised_train.describe()

review_count       rating    recommend
count   1102.000000  1102.000000  1102.000000
mean      72.245009     2.962341     0.500000
std       63.091170     0.945224     0.500227
min        0.000000     0.000000     0.000000
25%        7.000000     2.500000     0.000000
50%       79.000000     3.000000     0.500000
75%      119.000000     4.000000     1.000000
max      303.000000     5.000000     1.000000

In [94]:
semisupervised_train_for_model=semisupervised_train.drop(['id'], axis=1)
semisupervised_train_for_model

cuisine  review_count  rating  recommend
0      indian            98     4.5          1
1     italian            98     4.0          1
2     chinese            98     4.0          1
3     mexican            98     4.0          1
4     chinese            98     3.5          1
...       ...           ...     ...        ...
2894    greek             1     5.0          0
2895    latin             1     5.0          0
2896    latin             1     5.0          0
2897    latin             1     5.0          0
2898  persian             1     5.0          0

[2899 rows x 4 columns]

In [95]:
semisupervised_train_for_model = pd.get_dummies(semisupervised_train_for_model)
semisupervised_train_for_model

review_count  rating  recommend  cuisine_american  cuisine_chinese  \
0               98     4.5          1                 0                0   
1               98     4.0          1                 0                0   
2               98     4.0          1                 0                1   
3               98     4.0          1                 0                0   
4               98     3.5          1                 0                1   
...            ...     ...        ...               ...              ...   
2894             1     5.0          0                 0                0   
2895             1     5.0          0                 0                0   
2896             1     5.0          0                 0                0   
2897             1     5.0          0                 0                0   
2898             1     5.0          0                 0                0   

      cuisine_greek  cuisine_indian  cuisine_italian  cuisine_latin  \
0                 0               1                0              0   
1                 0               0                1              0   
2                 0               0                0              0   
3                 0               0                0              0   
4                 0               0                0              0   
...             ...             ...              ...            ...   
2894              1               0                0              0   
2895              0               0                0              1   
2896              0               0                0              1   
2897              0               0                0              1   
2898              0               0                0              0   

      cuisine_mexican  cuisine_persian  cuisine_spanish  
0                   0                0                0  
1                   0                0                0  
2                   0                0                0  
3                   1                0                0  
4                   0                0                0  
...               ...              ...              ...  
2894                0                0                0  
2895                0                0                0  
2896                0                0                0  
2897                0                0                0  
2898                0                1                0  

[2899 rows x 12 columns]

In [96]:
from sklearn.model_selection import train_test_split
train, validation = train_test_split(semisupervised_train_for_model, test_size=0.1, random_state=42)

In [97]:
train = pd.concat([train['recommend'], train.drop(['recommend'], axis=1)], axis=1)
validation = pd.concat([validation['recommend'], validation.drop(['recommend'], axis=1)], axis=1)

In [98]:
import sagemaker
import boto3
bucket = 'sagemaker-studio-s5jna6lkuup'

In [99]:
train.to_csv('train.csv', index=False, header=False)
validation.to_csv('validation.csv', index=False, header=False)

In [100]:
boto3.Session().resource('s3').Bucket(bucket).Object('train.csv').upload_file('train.csv')
boto3.Session().resource('s3').Bucket(bucket).Object('validation.csv').upload_file('validation.csv')

In [101]:
from sagemaker.predictor import csv_serializer
from sagemaker.amazon.amazon_estimator import get_image_uri
container = get_image_uri(boto3.Session().region_name, 'xgboost')
from sagemaker.predictor import csv_serializer

'get_image_uri' method will be deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK v2.
There is a more up to date SageMaker XGBoost image. To use the newer image, please set 'repo_version'='1.0-1'. For example:
	get_image_uri(region, 'xgboost', '1.0-1').


In [102]:
s3_input_train = sagemaker.s3_input(s3_data='s3://{}/train.csv'.format(bucket), content_type='csv')
s3_input_validation = sagemaker.s3_input(s3_data='s3://{}/validation.csv'.format(bucket), content_type='csv')

's3_input' class will be renamed to 'TrainingInput' in SageMaker Python SDK v2.
's3_input' class will be renamed to 'TrainingInput' in SageMaker Python SDK v2.


In [103]:
from sagemaker import get_execution_role
role = get_execution_role()
sess = sagemaker.Session()
xgb = sagemaker.estimator.Estimator(container,role,train_instance_count=1,train_instance_type='ml.m4.xlarge',output_path='s3://{}/output'.format(bucket),sagemaker_session=sess)
xgb.set_hyperparameters(max_depth=3,eta=0.2,gamma=4,min_child_weight=4,subsample=0.8,silent=0,objective='binary:logistic',num_round=20)
xgb.fit({'train': s3_input_train,'validation': s3_input_validation})

Parameter image_name will be renamed to image_uri in SageMaker Python SDK v2.


2020-08-05 21:17:50 Starting - Starting the training job...
2020-08-05 21:17:53 Starting - Launching requested ML instances......
2020-08-05 21:19:11 Starting - Preparing the instances for training......
2020-08-05 21:20:09 Downloading - Downloading input data...
2020-08-05 21:20:31 Training - Downloading the training image.Arguments: train
[2020-08-05:21:20:52:INFO] Running standalone xgboost training.
[2020-08-05:21:20:52:INFO] File size need to be processed in the node: 0.07mb. Available memory size in the node: 8493.64mb
[2020-08-05:21:20:52:INFO] Determined delimiter of CSV input is ','
[21:20:52] S3DistributionType set as FullyReplicated
[21:20:52] 2609x11 matrix with 28699 entries loaded from /opt/ml/input/data/train?format=csv&label_column=0&delimiter=,
[2020-08-05:21:20:52:INFO] Determined delimiter of CSV input is ','
[21:20:52] S3DistributionType set as FullyReplicated
[21:20:52] 290x11 matrix with 3190 entries loaded from /opt/ml/input/data/validation?format=csv&label_colum

In [104]:
xgb_predictor = xgb.deploy(initial_instance_count=1,instance_type='ml.m4.xlarge')

Parameter image will be renamed to image_uri in SageMaker Python SDK v2.


---------------!

In [105]:
xgb_predictor

In [107]:
xgb_predictor.content_type = 'text/csv'
xgb_predictor.serializer = csv_serializer

In [67]:
import numpy as np
def predict(data, rows=500):
    split_array = np.array_split(data, int(data.shape[0] / float(rows) + 1))
    predictions = ''
    for array in split_array:
        predictions = ','.join([predictions, xgb_predictor.predict(array).decode('utf-8')])
    return np.fromstring(predictions[1:], sep=',')

In [68]:
# validating using validation set 
val_label = validation['recommend']
validation = validation.drop(['recommend'], axis=1)

In [85]:
validation.to_numpy()[0]

array([125. ,   3.5,   0. ,   0. ,   1. ,   0. ,   0. ,   0. ,   0. ,
         0. ,   0. ])

In [79]:
pred_val = predict(validation.to_numpy())

In [80]:
pred_val

array([0.98542851, 0.0091162 , 0.98542851, 0.0091162 , 0.0091162 ,
       0.0091162 , 0.0091162 , 0.0091162 , 0.98542851, 0.0091162 ,
       0.0091162 , 0.98542851, 0.0091162 , 0.98542851, 0.0091162 ,
       0.0091162 , 0.0091162 , 0.0091162 , 0.98542851, 0.0091162 ,
       0.0091162 , 0.0091162 , 0.0091162 , 0.0091162 , 0.0091162 ,
       0.0091162 , 0.98542851, 0.0091162 , 0.0091162 , 0.0091162 ,
       0.0091162 , 0.0091162 , 0.0091162 , 0.0091162 , 0.0091162 ,
       0.0091162 , 0.0091162 , 0.0091162 , 0.0091162 , 0.0091162 ,
       0.0091162 , 0.0091162 , 0.0091162 , 0.0091162 , 0.0091162 ,
       0.0091162 , 0.0091162 , 0.0091162 , 0.0091162 , 0.0091162 ,
       0.0091162 , 0.0091162 , 0.0091162 , 0.98542851, 0.0091162 ,
       0.0091162 , 0.0091162 , 0.0091162 , 0.0091162 , 0.0091162 ,
       0.0091162 , 0.98542851, 0.98542851, 0.0091162 , 0.0091162 ,
       0.0091162 , 0.0091162 , 0.98542851, 0.0091162 , 0.98542851,
       0.0091162 , 0.98542851, 0.0091162 , 0.0091162 , 0.00911

In [81]:
pred_val[pred_val >= 0.5] = 1
pred_val[pred_val < 0.5] = 0
pred_val

array([1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1.,
       0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 0.

In [82]:
from sklearn.metrics import accuracy_score
accuracy_score(val_label, pred_val)

1.0

In [108]:
xgb_predictor.endpoint

'xgboost-2020-08-05-21-17-49-856'

In [109]:
#sagemaker.Session().delete_endpoint(xgb_predictor.endpoint)
#bucket_to_delete = boto3.resource('s3').Bucket(bucket)
#bucket_to_delete.objects.all().delete()